version: "3"
services:
  #web container
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      # if nested specify folder, reactproject
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  # tests container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    # override command
    command: ["npm", "run", "test"]
